#ifndef BOOT_CONFIG_H
#define BOOT_CONFIG_H

#include "sysflash.h"

#define BOOT_IMAGE_CONFIRM_OFFSET (FLASH_AREA_IMAGE_0_SIZE - 0x20U)
#define BOOT_IMAGE_CONFIRM_FIELD_SIZE 16U
#define BOOT_IMAGE_CONFIRM_FLAG_SET 0x01U

#define BOOT_ACTIVE_SLOT_MAGIC 0x41534C54U
#define BOOT_ACTIVE_SLOT_CHECKSUM_XOR 0x5A5AA5A5U

#endif /* BOOT_CONFIG_H */
