#ifndef UDS_PROTOCOL_H
#define UDS_PROTOCOL_H

#include "security_access_level.h"
#include "payload_id_format.h"

/*
 * Shared UDS wire contract between the ECU firmware (can/) and the Linux
 * gateway (gateway/).  This header is the single source of truth for the
 * diagnostic protocol values; both trees include it and must not redefine
 * these macros locally.
 *
 * Naming follows the ECU tree (UPPER_SNAKE with U suffix).
 */

/* --- Session timing (ISO 14229) --- */
#define P2_SERVER_DEFAULT_MS 50U
#define P2_STAR_SERVER_DEFAULT_MS 5000U
/* ISO 14229 encodes P2*ServerMax in 10 ms units on the wire. */
#define P2_STAR_SERVER_DEFAULT_WIRE (P2_STAR_SERVER_DEFAULT_MS / 10U)
#define UDS_RESPONSE_PENDING_REPEAT_INTERVAL_MS 1500U
#define UDS_RESPONSE_PENDING_MAX_COUNT 8U
#define S3_SERVER_DEFAULT 5000U

/* --- Service identifiers --- */
#define SID_DIAGNOSTIC_SESSION_CONTROL 0x10U
#define SID_ECU_RESET 0x11U
#define SID_READ_DATA_BY_IDENTIFIER 0x22U
#define SID_SECURITY_ACCESS 0x27U
#define SID_ROUTINE_CONTROL 0x31U
#define SID_REQUEST_DOWNLOAD 0x34U
#define SID_TRANSFER_DATA 0x36U
#define SID_REQUEST_TRANSFER_EXIT 0x37U
#define SID_TESTER_PRESENT 0x3EU
#define SID_POSITIVE_RESPONSE_MASK 0x40U
#define NEGATIVE_RESPONSE_SID 0x7FU
#define UDS_NEGATIVE_RESPONSE_LENGTH 3U
#define UDS_SUBFUNCTION_SUPPRESS_POSITIVE_RESPONSE_MASK 0x80U
#define UDS_SUBFUNCTION_VALUE_MASK 0x7FU

/* --- Positive response SIDs --- */
#define SID_DIAGNOSTIC_SESSION_CONTROL_POS 0x50U
#define SID_ECU_RESET_POS 0x51U
#define SID_READ_DATA_BY_IDENTIFIER_POS 0x62U
#define SID_SECURITY_ACCESS_POS 0x67U
#define SID_ROUTINE_CONTROL_POS 0x71U
#define SID_REQUEST_DOWNLOAD_POS 0x74U
#define SID_TRANSFER_DATA_POS 0x76U
#define SID_REQUEST_TRANSFER_EXIT_POS 0x77U
#define SID_TESTER_PRESENT_POS 0x7EU

/* --- Diagnostic sessions --- */
#define SESSION_DEFAULT 0x01U
#define SESSION_PROGRAMMING 0x02U
#define SESSION_EXTENDED 0x03U
#define SUB_HARD_RESET 0x01U

/* --- SecurityAccess subfunction levels (from security_access_level.h) --- */

/* --- SecurityAccess seed challenge shape (can/security/security_seed.h) --- */
#define SECURITY_ACCESS_SEED_SIZE 4U

/* --- Download control --- */
#define DOWNLOAD_DATA_FORMAT_ID 0x00U
#define DOWNLOAD_ADDR_LEN_FORMAT_ID 0x44U
#define DOWNLOAD_MAX_BLOCK_LEN_FORMAT_ID 0x20U
#define DOWNLOAD_MEMORY_ADDRESS 0U
#define UDS_REQUEST_DOWNLOAD_REQUEST_LEN (11U + PAYLOAD_ID_SIZE)
#define UDS_REQUEST_DOWNLOAD_PAYLOAD_ID_OFFSET 11U

/* --- Download preparation routine --- */
#define ROUTINE_CONTROL_START 0x01U
#define ROUTINE_CONTROL_REQUEST_RESULTS 0x03U
#define ROUTINE_ID_PREPARE_DOWNLOAD 0xF001U
#define ROUTINE_PREPARE_DOWNLOAD_STATUS_READY 0x00U
#define ROUTINE_PREPARE_DOWNLOAD_STATUS_PENDING 0x01U
#define UDS_ROUTINE_CONTROL_REQUEST_LEN 4U
#define UDS_PREPARE_DOWNLOAD_ROUTINE_REQUEST_LEN \
    (UDS_ROUTINE_CONTROL_REQUEST_LEN + 4U + PAYLOAD_ID_SIZE)
#define UDS_PREPARE_DOWNLOAD_ROUTINE_SIZE_OFFSET 4U
#define UDS_PREPARE_DOWNLOAD_ROUTINE_PAYLOAD_ID_OFFSET 8U
#define UDS_PREPARE_DOWNLOAD_ROUTINE_RESULT_LEN 5U

/* Complete positive response offsets include the 0x74 SID. */
#define UDS_REQUEST_DOWNLOAD_RESPONSE_LEN 9U
#define UDS_REQUEST_DOWNLOAD_RESPONSE_MAX_BLOCK_OFFSET 2U
#define UDS_REQUEST_DOWNLOAD_RESPONSE_TARGET_SLOT_OFFSET 4U
#define UDS_REQUEST_DOWNLOAD_RESPONSE_RESUME_OFFSET 5U

/* --- Negative response codes --- */
#define NRC_GENERAL_REJECT 0x10U
#define NRC_SERVICE_NOT_SUPPORTED 0x11U
#define NRC_SUBFUNCTION_NOT_SUPPORTED 0x12U
#define NRC_INCORRECT_MESSAGE_LENGTH 0x13U
#define NRC_BUSY_REPEAT_REQUEST 0x21U
#define NRC_CONDITIONS_NOT_CORRECT 0x22U
#define NRC_REQUEST_SEQUENCE_ERROR 0x24U
#define NRC_REQUEST_OUT_OF_RANGE 0x31U
#define NRC_SECURITY_ACCESS_DENIED 0x33U
#define NRC_INVALID_KEY 0x35U
#define NRC_EXCEED_NUMBER_OF_ATTEMPTS 0x36U
#define NRC_REQUIRED_TIME_DELAY_NOT_EXPIRED 0x37U
#define NRC_UPLOAD_DOWNLOAD_NOT_ACCEPTED 0x70U
#define NRC_GENERAL_PROGRAMMING_FAILURE 0x72U
#define NRC_WRONG_BLOCK_SEQUENCE_COUNTER 0x73U
#define NRC_RESPONSE_PENDING 0x78U

/* --- Data identifiers --- */
#define DID_BOOT_VERSION 0xF180U
#define DID_APP_VERSION 0xF181U
#define DID_UPDATER_VERSION 0xF182U
#define DID_ACTIVE_SLOT 0xF1A0U
#define DID_CONFIRM_RESULT 0xF1A8U

#endif /* UDS_PROTOCOL_H */
